version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - esnet

  squid:
    build:
      context: ./squid
    container_name: squid
    ports:
      - "3228:3128"
    volumes:
      - spool:/var/spool/squid3
      - squidlogs:/var/log/squid3
      - guardlogs:/var/log/squidguard
    networks:
      - esnet
      - external
    restart: always


  squid_auth:
    build:
      context: ./squid_auth
    container_name: squid_auth
    ports:
      - "3328:3128"
    volumes:
      - spool_auth:/var/spool/squid3
      - squidlogs_auth:/var/log/squid3
      - guardlogs_auth:/var/log/squidguard
    networks:
      - esnet
      - external
    restart: always
volumes:
  spool:
  squidlogs:
  guardlogs:
  spool_auth:
  squidlogs_auth:
  guardlogs_auth:
networks:
  esnet:
    internal: true
  external: